"""empty message

Revision ID: 80de6af40bb2
Revises: 9a7d9ab2faae
Create Date: 2025-02-22 09:25:05.885558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80de6af40bb2'
down_revision = '9a7d9ab2faae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
