"""empty message

Revision ID: 87a94b199418
Revises: f3cf80b1de8d
Create Date: 2025-02-21 19:10:42.855653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a94b199418'
down_revision = 'f3cf80b1de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_home_goals_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint('matches_home_goals_key', ['home_goals'])

    # ### end Alembic commands ###
