"""empty message

Revision ID: aff1fe09b86f
Revises: c0da9eefebe1
Create Date: 2025-03-12 11:21:26.797426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff1fe09b86f'
down_revision = 'c0da9eefebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('is_scoutable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_scoutable', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('position',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
