"""empty message

Revision ID: c0da9eefebe1
Revises: 56ecd780fc17
Create Date: 2025-03-12 10:41:14.031961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0da9eefebe1'
down_revision = '56ecd780fc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.drop_column('market_value')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_value', sa.Integer(), nullable=False, default=1000000))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('market_value')

    with op.batch_alter_table('fantasy_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_value', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
