"""empty message

Revision ID: d4931aa25dae
Revises: 80de6af40bb2
Create Date: 2025-02-22 12:00:27.524737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4931aa25dae'
down_revision = '80de6af40bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('dribbles_attemps', sa.Integer(), nullable=False),
    sa.Column('dribbles_success', sa.Integer(), nullable=False),
    sa.Column('dribbles_past', sa.Integer(), nullable=False),
    sa.Column('fouls_drawn', sa.Integer(), nullable=False),
    sa.Column('fouls_comitted', sa.Integer(), nullable=False),
    sa.Column('cards_yellow', sa.Integer(), nullable=False),
    sa.Column('cards_red', sa.Integer(), nullable=False),
    sa.Column('penalty_commited', sa.Integer(), nullable=False),
    sa.Column('passes_accuracy', sa.Integer(), nullable=False),
    sa.Column('tackles_total', sa.Integer(), nullable=False),
    sa.Column('tackles_blocks', sa.Integer(), nullable=False),
    sa.Column('tackles_interceptions', sa.Integer(), nullable=False),
    sa.Column('duels_total', sa.Integer(), nullable=False),
    sa.Column('duels_won', sa.Integer(), nullable=False),
    sa.Column('penalty_scored', sa.Integer(), nullable=False),
    sa.Column('penalty_saved', sa.Integer(), nullable=False),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('goals_total', sa.Integer(), nullable=False),
    sa.Column('goals_concedes', sa.Integer(), nullable=False),
    sa.Column('goals_assistes', sa.Integer(), nullable=False),
    sa.Column('goals_saved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.uid'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.uid'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    # ### end Alembic commands ###
