"""empty message

Revision ID: dec281e1a728
Revises: 87a94b199418
Create Date: 2025-02-21 19:12:02.153518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec281e1a728'
down_revision = '87a94b199418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint('matches_date_key', ['date'])

    # ### end Alembic commands ###
