"""empty message

Revision ID: f3cf80b1de8d
Revises: 619fcd4734a2
Create Date: 2025-02-21 19:06:29.703446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cf80b1de8d'
down_revision = '619fcd4734a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('matches_is_home_winner_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint('matches_is_home_winner_key', ['is_home_winner'])

    # ### end Alembic commands ###
